---
- name: become root and setup wireguard
  import_tasks: root.yml
  become: true
  when: wrt_wg_nets |default([])
  tags:
    - wrt_wg_all
    - wrt_wireguard_all

- name: run postponed handlers now
  meta: flush_handlers
  tags:
    - wrt_wg_all
    - wrt_wireguard_all
...
